const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const vendors = [
  {
    name: 'Pho Hoa Pasteur',
    slug: 'pho-hoa-pasteur-q3',
    description: 'Traditional southern-style pho with clear, aromatic broth.',
    latitude: 10.7851,
    longitude: 106.6957,
    addressText: '260C Pasteur Street',
    district: 'District 3',
    city: 'Ho Chi Minh City',
    category: 'Pho',
    priceMin: 70000,
    priceMax: 120000,
    openHoursJson: { daily: '06:00-22:00' },
    status: 'APPROVED',
    aiSummary: 'Reliable classic pho spot for breakfast and late dinner.',
  },
  {
    name: 'Com Tam Ba Ghien',
    slug: 'com-tam-ba-ghien-tan-binh',
    description: 'Broken rice plates known for large grilled pork chops.',
    latitude: 10.7995,
    longitude: 106.6531,
    addressText: '84 Dang Van Ngu Street',
    district: 'Tan Binh District',
    city: 'Ho Chi Minh City',
    category: 'Com Tam',
    priceMin: 50000,
    priceMax: 95000,
    openHoursJson: { daily: '07:00-21:30' },
    status: 'APPROVED',
    aiSummary: 'Famous com tam with generous portions and smoky grilled meat.',
  },
  {
    name: 'Bun Bo Hue O Xuan',
    slug: 'bun-bo-hue-o-xuan-binh-thanh',
    description: 'Spicy Hue beef noodle soup with rich lemongrass broth.',
    latitude: 10.8058,
    longitude: 106.7144,
    addressText: '12 Dinh Tien Hoang Street',
    district: 'Binh Thanh District',
    city: 'Ho Chi Minh City',
    category: 'Bun Bo Hue',
    priceMin: 55000,
    priceMax: 90000,
    openHoursJson: { daily: '06:30-21:00' },
    status: 'APPROVED',
    aiSummary: 'Comforting spicy noodle soup with balanced broth depth.',
  },
  {
    name: 'Hu Tieu Nam Vang Thanh Dat',
    slug: 'hu-tieu-nam-vang-thanh-dat-q10',
    description: 'Dry and soup hu tieu with pork, shrimp, and quail egg.',
    latitude: 10.7747,
    longitude: 106.6678,
    addressText: '34 Nguyen Tri Phuong Street',
    district: 'District 10',
    city: 'Ho Chi Minh City',
    category: 'Hu Tieu',
    priceMin: 50000,
    priceMax: 85000,
    openHoursJson: { daily: '06:00-22:00' },
    status: 'APPROVED',
    aiSummary: 'Popular hu tieu place with both dry and broth options.',
  },
  {
    name: 'Banh Mi Huynh Hoa',
    slug: 'banh-mi-huynh-hoa-q1',
    description: 'Loaded Vietnamese baguette with pate and cold cuts.',
    latitude: 10.7732,
    longitude: 106.6915,
    addressText: '26 Le Thi Rieng Street',
    district: 'District 1',
    city: 'Ho Chi Minh City',
    category: 'Banh Mi',
    priceMin: 58000,
    priceMax: 75000,
    openHoursJson: { daily: '14:30-23:00' },
    status: 'APPROVED',
    aiSummary: 'Iconic banh mi known for rich fillings and long queues.',
  },
  {
    name: 'Bun Thit Nuong Chi Tuyen',
    slug: 'bun-thit-nuong-chi-tuyen-phu-nhuan',
    description: 'Grilled pork vermicelli bowls with fresh herbs and fish sauce.',
    latitude: 10.7992,
    longitude: 106.679,
    addressText: '9 Nguyen Dinh Chieu Street',
    district: 'Phu Nhuan District',
    city: 'Ho Chi Minh City',
    category: 'Bun Thit Nuong',
    priceMin: 45000,
    priceMax: 70000,
    openHoursJson: { daily: '09:00-21:00' },
    status: 'APPROVED',
    aiSummary: 'Balanced bun thit nuong with fragrant grilled pork.',
  },
  {
    name: 'Banh Xeo 46A',
    slug: 'banh-xeo-46a-dinh-cong-trang',
    description: 'Crispy southern pancakes served with herbs and dipping sauce.',
    latitude: 10.7903,
    longitude: 106.6934,
    addressText: '46A Dinh Cong Trang Street',
    district: 'District 1',
    city: 'Ho Chi Minh City',
    category: 'Banh Xeo',
    priceMin: 90000,
    priceMax: 140000,
    openHoursJson: { daily: '10:00-21:30' },
    status: 'APPROVED',
    aiSummary: 'Well-known crispy banh xeo with plenty of greens.',
  },
  {
    name: 'Oc Dao',
    slug: 'oc-dao-nguyen-thai-hoc-q1',
    description: 'Sea snail and shellfish dishes with bold garlic and butter sauces.',
    latitude: 10.7679,
    longitude: 106.6895,
    addressText: '212B Nguyen Trai Street',
    district: 'District 1',
    city: 'Ho Chi Minh City',
    category: 'Seafood',
    priceMin: 70000,
    priceMax: 180000,
    openHoursJson: { daily: '15:00-23:00' },
    status: 'APPROVED',
    aiSummary: 'Busy evening seafood spot with many sauce options.',
  },
  {
    name: 'Che Ha Ky',
    slug: 'che-ha-ky-q5',
    description: 'Traditional sweet dessert soups and herbal drinks.',
    latitude: 10.7543,
    longitude: 106.6639,
    addressText: '138 Chau Van Liem Street',
    district: 'District 5',
    city: 'Ho Chi Minh City',
    category: 'Dessert',
    priceMin: 20000,
    priceMax: 45000,
    openHoursJson: { daily: '10:00-22:00' },
    status: 'APPROVED',
    aiSummary: 'Classic Chinatown dessert stop for sweet soups and drinks.',
  },
  {
    name: 'Lau De 404',
    slug: 'lau-de-404-nguyen-chi-thanh-q10',
    description: 'Goat hotpot and grilled dishes for group meals.',
    latitude: 10.7637,
    longitude: 106.6714,
    addressText: '404 Nguyen Chi Thanh Street',
    district: 'District 10',
    city: 'Ho Chi Minh City',
    category: 'Hotpot',
    priceMin: 120000,
    priceMax: 280000,
    openHoursJson: { daily: '11:00-23:00' },
    status: 'APPROVED',
    aiSummary: 'Casual spot for hearty goat hotpot and grilled plates.',
  },
  {
    name: 'Mi Quang My Son',
    slug: 'mi-quang-my-son-q3',
    description: 'Central-style turmeric noodles with shrimp and pork.',
    latitude: 10.7817,
    longitude: 106.6849,
    addressText: '96 Vo Van Tan Street',
    district: 'District 3',
    city: 'Ho Chi Minh City',
    category: 'Mi Quang',
    priceMin: 50000,
    priceMax: 85000,
    openHoursJson: { daily: '07:00-21:00' },
    status: 'APPROVED',
    aiSummary: 'Comforting central Vietnamese noodles with rich toppings.',
  },
  {
    name: 'Bo La Lot Co Lien',
    slug: 'bo-la-lot-co-lien-go-vap',
    description: 'Betel-leaf wrapped beef served with vermicelli and rice paper.',
    latitude: 10.8391,
    longitude: 106.6684,
    addressText: '31 Quang Trung Street',
    district: 'Go Vap District',
    city: 'Ho Chi Minh City',
    category: 'Grill',
    priceMin: 60000,
    priceMax: 110000,
    openHoursJson: { daily: '16:00-22:00' },
    status: 'APPROVED',
    aiSummary: 'Local favorite for smoky bo la lot in the evening.',
  },
];

async function main() {
  for (const vendor of vendors) {
    await prisma.vendor.upsert({
      where: { slug: vendor.slug },
      update: vendor,
      create: vendor,
    });
  }

  console.log(`Seeded ${vendors.length} vendors.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
